### ISSUE TITLE
Benthos dies in stream mode

### ISSUE THREAD

**Issue by mariosant** [benthosdev/benthos#1248]
I tried migrating a benthos instance I got with the new v4 and getting this error https://pastebin.com/15wc7MwY

Benthos runs on stream mode. No metric processor. A single stream and about 4-5 resources. All streams are configured via files.

**Comment by mihaitodor** [comment]
I was able to reproduce it like so:

```shell
mihaitodor@brainiac:~$ cat foo.yaml
processor_resources:
  - label: foo
    bloblang: root = this
mihaitodor@brainiac:~$ cat stream.yaml
input:
  stdin: {}

pipeline:
  processors:
    - bloblang: 'root = {}'

output:
  stdout: {}
mihaitodor@brainiac:~$ benthos -r foo.yaml streams stream.yaml
panic: inconsistent label cardinality: expected 2 label values but got 3 in []string{"", "root.pipeline.processors.0", "stream"}

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*CounterVec).WithLabelValues(0x100ef67?, {0xc000ad0a20?, 0x358ffc0?, 0xc001482b01?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/counter.go:248 +0x85
github.com/benthosdev/benthos/v4/internal/impl/prometheus.(*promCounterVec).With(0x12?, {0xc000ad0a20?, 0x3?, 0x3?})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/impl/prometheus/metrics_prometheus.go:108 +0x25
github.com/benthosdev/benthos/v4/internal/component/metrics.(*combinedCounterVec).With(0xc000ca9420, {0xc000ad0a20, 0x3, 0x3})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/component/metrics/combine.go:93 +0x3c
github.com/benthosdev/benthos/v4/internal/component/metrics.(*Namespaced).GetCounter(0xc000f96cf0, {0x395501b?, 0x0?})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/component/metrics/namespaced.go:145 +0x82
github.com/benthosdev/benthos/v4/internal/component/processor.NewV2BatchedToV1Processor({0x3937588, 0x8}, {0x4251390?, 0xc001247f20}, {0x426c870, 0xc000f96cf0})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/component/processor/processor_v2.go:149 +0x139
github.com/benthosdev/benthos/v4/internal/old/processor.init.3.func1({{0x4237870, 0x0}, {0xc00163dce0, 0x8}, {{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, ...}, ...}, ...)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/old/processor/bloblang.go:27 +0x9d
github.com/benthosdev/benthos/v4/internal/interop/legacy.init.0.func3.1({{0x4237870, 0x0}, {0xc00163dce0, 0x8}, {{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, ...}, ...}, ...)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/interop/legacy/package.go:42 +0xe7
github.com/benthosdev/benthos/v4/internal/bundle.(*ProcessorSet).Init(_, {{0x4237870, 0x0}, {0xc00163dce0, 0x8}, {{0x0, 0x0}, {0x0, 0x0}}, {{0x0, ...}, ...}, ...}, ...)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/bundle/processors.go:77 +0x1bc
github.com/benthosdev/benthos/v4/internal/bundle.(*Environment).ProcessorInit(...)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/bundle/processors.go:29
github.com/benthosdev/benthos/v4/internal/manager.(*Type).NewProcessor(_, {{0x4237870, 0x0}, {0xc00163dce0, 0x8}, {{0x0, 0x0}, {0x0, 0x0}}, {{0x0, ...}, ...}, ...})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/manager/type.go:550 +0x7a
github.com/benthosdev/benthos/v4/internal/old/processor.New({{0x4237870, 0x0}, {0xc00163dce0, 0x8}, {{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, ...}, ...}, ...)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/old/processor/constructor.go:276 +0x248
github.com/benthosdev/benthos/v4/internal/pipeline.New({0x4237870?, {0xc000f9ca80?, 0xc00163dcc0?, 0x5?}}, {0x4279038, 0xc0001571e0})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/pipeline/constructor.go:40 +0x786
github.com/benthosdev/benthos/v4/internal/stream.(*Type).start(0xc000fe8000)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/stream/type.go:103 +0x2f2
github.com/benthosdev/benthos/v4/internal/stream.New({{{0x4237870, 0x0}, {0xc00163dcc0, 0x5}, {{0x59ff918, 0x0, 0x0}, {0x4237870, 0x0}, {0x0, ...}, ...}, ...}, ...}, ...)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/stream/type.go:44 +0x117
github.com/benthosdev/benthos/v4/internal/stream/manager.(*Type).Create(_, {_, _}, {{{0x4237870, 0x0}, {0xc00163dcc0, 0x5}, {{0x59ff918, 0x0, 0x0}, ...}, ...}, ...})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/stream/manager/type.go:152 +0x2b9
github.com/benthosdev/benthos/v4/internal/cli.initStreamsMode(0x1, 0x0, 0x9f?, 0xc0006d0a90, 0x0?, {0x4274898, 0xc00014cf08}, 0x1?)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/cli/service.go:94 +0x2e5
github.com/benthosdev/benthos/v4/internal/cli.cmdService({0x0?, 0xc0006d0750?}, {0xc0016f8bf0?, 0x598e2c0?, 0x392cdca?}, {0x0?, 0x392cdca?, 0x4?}, {0x0, 0x0}, ...)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/cli/service.go:320 +0xaa5
github.com/benthosdev/benthos/v4/internal/cli.Run.func4(0xc000f3a6c0)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/cli/run.go:303 +0x216
github.com/urfave/cli/v2.(*Command).Run(0xc0017ae6c0, 0xc000f3a5c0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc00072aea0, {0x425efe0?, 0xc00019c008}, {0xc0001a0000, 0x5, 0x5})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/benthosdev/benthos/v4/internal/cli.Run()
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/cli/run.go:332 +0xcc5
main.main()
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/cmd/benthos/main.go:11 +0x17
mihaitodor@brainiac:~$
```

**Comment by Jeffail** [comment]
Thanks both, nice catch and great reproducible example, should have this fixed with: https://github.com/benthosdev/benthos/commit/1dbf284a8025e3f07111707f3bdbe35e8c53d573
