### ISSUE TITLE
Concurrent map read / write access panic in `benthos blobl server`

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1825]
My best guess is that I was typing too fast 😅 

```
benthntodor@LAMU02XK0R6JGH6:~$ benthos blobl server
2023/03/31 17:23:25 Serving at: http://localhost:4195
fatal error: concurrent map read and map write

goroutine 16 [running]:
github.com/benthosdev/benthos/v4/internal/bloblang/query.NewVarFunction.func1({0xc001625fb0, 0xc0001fd2f0, 0x0, {0x103f132e8, 0xc000b8c708}, {0x103f2df90, 0xc0011d8660}, 0xc0004ecc00, 0xc00099c900, 0x0, ...})
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/functions.go:891 +0x45
github.com/benthosdev/benthos/v4/internal/bloblang/query.closureFunction.Exec(...)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/function_ctor.go:61
github.com/benthosdev/benthos/v4/internal/bloblang/query.registerSimpleMethod.func1.1({0xc001625fb0, 0xc0001fd2f0, 0x0, {0x103f132e8, 0xc000b8c708}, {0x103f2df90, 0xc0011d8660}, 0xc0004ecc00, 0xc00099c900, 0x0, ...})
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/method_ctor.go:20 +0x7a
github.com/benthosdev/benthos/v4/internal/bloblang/query.closureFunction.Exec(...)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/function_ctor.go:61
github.com/benthosdev/benthos/v4/internal/bloblang/mapping.(*Executor).ExecOnto(0xc0002a7f90, {0xc001625fb0, 0xc0001fd2f0, 0x0, {0x103f132e8, 0xc000b8c708}, {0x103f2df90, 0xc0011d8660}, 0xc0004ecc00, 0xc00099c900, ...}, ...)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/mapping/executor.go:300 +0x155
github.com/benthosdev/benthos/v4/internal/cli/blobl.(*execCache).executeMapping(0xc00045b740, 0xc0002a7f90, 0x0, 0x1, {0xc001368120, 0x19, 0x20})
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/cli/blobl/cli.go:157 +0x3b2
github.com/benthosdev/benthos/v4/internal/cli/blobl.runServer.func1({0x103f1e7a0, 0xc00139bce0}, 0xc000730d00)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/cli/blobl/server.go:187 +0x319
net/http.HandlerFunc.ServeHTTP(0xc00139bce0?, {0x103f1e7a0?, 0xc00139bce0?}, 0x100076860?)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x103f1e7a0, 0xc00139bce0}, 0xc000730d00)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0x103f126b8?}, {0x103f1e7a0, 0xc00139bce0}, 0xc000730d00)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000f01200, {0x103f20698, 0xc0001fdb90})
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:3089 +0x5ed

goroutine 1 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x12fcff810, 0x72)
	/usr/local/Cellar/go/1.20.2/libexec/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000a9c500?, 0x16?, 0x0)
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000a9c500)
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_unix.go:614 +0x2bd
net.(*netFD).accept(0xc000a9c500)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0011d8720)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).Accept(0xc0011d8720)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/tcpsock.go:297 +0x3d
net/http.(*Server).Serve(0xc000dae690, {0x103f1e530, 0xc0011d8720})
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:3059 +0x385
net/http.(*Server).ListenAndServe(0xc000dae690)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:2988 +0x7d
github.com/benthosdev/benthos/v4/internal/cli/blobl.runServer(0xc0017c3200?)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/cli/blobl/server.go:238 +0x737
github.com/urfave/cli/v2.(*Command).Run(0xc0017c3200, 0xc0016f3e00)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.11.0/command.go:169 +0x648
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0012d2000, 0xc0016f3ac0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.11.0/app.go:526 +0xd05
github.com/urfave/cli/v2.(*Command).startApp(0xc0017c30e0, 0xc0016f3ac0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.11.0/command.go:287 +0x79b
github.com/urfave/cli/v2.(*Command).Run(0xc001713e08?, 0xc000db1690?)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.11.0/command.go:95 +0xaa
github.com/urfave/cli/v2.(*App).RunContext(0xc0012d9dc0, {0x103f20628?, 0xc00012e010}, {0xc00011c180, 0x3, 0x3})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.11.0/app.go:378 +0xfa6
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.11.0/app.go:251
github.com/benthosdev/benthos/v4/internal/cli.Run()
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/cli/run.go:354 +0xdb8
main.main()
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/cmd/benthos/main.go:11 +0x17

goroutine 10 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf

goroutine 11 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000a9c080)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0xad
created by go.opencensus.io/stats/view.init.0
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x96

goroutine 13 [chan receive, 4 minutes]:
github.com/benthosdev/benthos/v4/internal/cli/blobl.runServer.func3()
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/cli/blobl/server.go:234 +0x91
created by github.com/benthosdev/benthos/v4/internal/cli/blobl.runServer
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/cli/blobl/server.go:229 +0x72a

goroutine 50 [syscall, 4 minutes]:
os/signal.signal_recv()
	/usr/local/Cellar/go/1.20.2/libexec/src/runtime/sigqueue.go:149 +0x28
os/signal.loop()
	/usr/local/Cellar/go/1.20.2/libexec/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/local/Cellar/go/1.20.2/libexec/src/os/signal/signal.go:151 +0x2a

goroutine 39 [runnable]:
github.com/benthosdev/benthos/v4/internal/bloblang/query.IClone({0x102c7bd00?, 0xc0005c42a0?})
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/type_helpers.go:553 +0x225
github.com/benthosdev/benthos/v4/internal/bloblang/query.mergeMethod.func1({0xc000e9cff0, 0xc0001fd2f0, 0x0, {0x103f132e8, 0xc0005c4270}, {0x103f2df90, 0xc0011d8660}, 0xc0007d8c00, 0xc0011ef480, 0x0, ...})
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/methods_structured.go:1010 +0xc5
github.com/benthosdev/benthos/v4/internal/bloblang/query.closureFunction.Exec(...)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/function_ctor.go:61
github.com/benthosdev/benthos/v4/internal/bloblang/query.wrapMethodCtorWithDynamicArgs.func1({0xc000e9cff0, 0xc0001fd2f0, 0x0, {0x103f132e8, 0xc0005c4270}, {0x103f2df90, 0xc0011d8660}, 0xc0007d8c00, 0xc0011ef480, 0x0, ...})
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/method_set.go:179 +0xf8
github.com/benthosdev/benthos/v4/internal/bloblang/query.closureFunction.Exec(...)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/query/function_ctor.go:61
github.com/benthosdev/benthos/v4/internal/bloblang/mapping.(*Executor).ExecOnto(0xc000b28050, {0xc000e9cff0, 0xc0001fd2f0, 0x0, {0x103f132e8, 0xc0005c4270}, {0x103f2df90, 0xc0011d8660}, 0xc0007d8c00, 0xc0011ef480, ...}, ...)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/bloblang/mapping/executor.go:300 +0x155
github.com/benthosdev/benthos/v4/internal/cli/blobl.(*execCache).executeMapping(0xc00045b740, 0xc000b28050, 0x0, 0x1, {0xc001702180, 0x19, 0x20})
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/cli/blobl/cli.go:157 +0x3b2
github.com/benthosdev/benthos/v4/internal/cli/blobl.runServer.func1({0x103f1e7a0, 0xc00124bce0}, 0xc000fdc700)
	/private/tmp/benthos-20230315-4695-wtsiaq/benthos-4.13.0/internal/cli/blobl/server.go:187 +0x319
net/http.HandlerFunc.ServeHTTP(0xc00124bce0?, {0x103f1e7a0?, 0xc00124bce0?}, 0x100076860?)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x103f1e7a0, 0xc00124bce0}, 0xc000fdc700)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0x103f126b8?}, {0x103f1e7a0, 0xc00124bce0}, 0xc000fdc700)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc001822000, {0x103f20698, 0xc0001fdb90})
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:3089 +0x5ed

goroutine 234 [IO wait]:
internal/poll.runtime_pollWait(0x12fcff630, 0x72)
	/usr/local/Cellar/go/1.20.2/libexec/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000b8a000?, 0xc000374101?, 0x0)
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000b8a000, {0xc000374101, 0x1, 0x1})
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc000b8a000, {0xc000374101?, 0xc00141c680?, 0xc00146af48?})
	/usr/local/Cellar/go/1.20.2/libexec/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0000140c0, {0xc000374101?, 0xc0013043d0?, 0xc001226140?})
	/usr/local/Cellar/go/1.20.2/libexec/src/net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc0003740f0)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:674 +0x3f
created by net/http.(*connReader).startBackgroundRead
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:670 +0xca

goroutine 219 [IO wait]:
internal/poll.runtime_pollWait(0x12fcff720, 0x72)
	/usr/local/Cellar/go/1.20.2/libexec/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000a9c580?, 0xc0001fdcc1?, 0x0)
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000a9c580, {0xc0001fdcc1, 0x1, 0x1})
	/usr/local/Cellar/go/1.20.2/libexec/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc000a9c580, {0xc0001fdcc1?, 0xc00141c9c0?, 0xc001468f48?})
	/usr/local/Cellar/go/1.20.2/libexec/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00065b1b0, {0xc0001fdcc1?, 0xc0013043d0?, 0xc00103fe50?})
	/usr/local/Cellar/go/1.20.2/libexec/src/net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc0001fdcb0)
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:674 +0x3f
created by net/http.(*connReader).startBackgroundRead
	/usr/local/Cellar/go/1.20.2/libexec/src/net/http/server.go:670 +0xca
ntodor@LAMU02XK0R6JGH6:~$
```

**Comment by Jeffail** [comment]
Looks like concurrent requests that use the same variables map. I'm not entirely sure why I originally chose to persist variables across mapping calls, maybe as a cool feature. I think I'll probably just get rid of it for now as it's odd behaviour to begin with.

**Comment by Jeffail** [comment]
Should be fixed in: https://github.com/benthosdev/benthos/commit/849b2c028d06673a45cc9d1d0981326b9ad23652
